# Principal View Configuration Lint Rules
# See: https://github.com/principal-ai/principal-view

# File patterns to include
include:
  - "architecture.canvas"

# Path to component library (optional)
library: ".principal-views/library.yaml"

# Rule configuration
rules:
  no-unknown-fields: error
  required-metadata: error
  valid-node-types: error
  valid-edge-types: error
